# fly.toml app configuration file generated for anon-my-rpc on 2023-06-16T21:05:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anon-my-rpc"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
